version: '3'

services:
  selenium:
    image: selenium/standalone-chrome
    shm_size: 2gb
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "4444:4444"

  postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=kickstart
      - POSTGRES_PASSWORD=kickstart
      - POSTGRES_DB=kickstart_acceptance