---
resources:
  - name: sources
    type: git
    icon: github
    source:
      uri: https://github.com/bee-software/kickstart.git
      branch: master

  - name: selenium-chrome
    type: registry-image
    icon: docker
    source:
      repository: selenium/standalone-chrome
#      tag: 96.0

  - name: postgres
    type: registry-image
    icon: docker
    source:
      repository: postgres

jobs:
  - name: test
    plan:
      - get: sources
        params:
          depth: 1
        trigger: true
      - task: tests
        file: sources/scripts/ci/test.yml

  - name: acceptance
    plan:
      - in_parallel:
        - get: sources
          params:
            depth: 1
          passed: [test]
          trigger: true
        - get: selenium-chrome
          params: {format: oci}
      - task: acceptance-tests
        privileged: true
        file: sources/scripts/ci/acceptance.yml
