---
platform: linux

image_resource:
  type: docker-image
  source: {repository: gradle, tag: 7.0.1-jdk16}

# Cache the Gradle repository directory
caches:
  - path: $HOME/.gradle

inputs:
  - name: sources

run:
  path: sources/ci/build.sh