---
platform: linux

image_resource:
  type: docker-image
  source: { repository: selenium/node-chrome, tag: latest }

params:
  START_XVFB: false

# Cache the Gradle repository directory
caches:
  - path: $HOME/.gradle/caches/
  - path: $HOME/.gradle/wrapper/

inputs:
  - name: sources

run:
  user: root
  path: sources/ci/build.sh
