---
resources:
  - name: code
    icon: github
    type: git
    source:
      uri: https://github.com/bee-software/kickstart.git
      branch: master

  - name: gradle
    type: docker-image
    source:
      repository: gradle
      tag: 7.3.0-jdk17

jobs:
  - name: test
    plan:
      - get: code
        params:
          depth: 1
        trigger: true
      - task: tests
        file: code/ci/test.yml
