package security

import com.vtence.kabinet.*
import kickstart.security.PasswordHash
import kickstart.security.User
import kickstart.security.Username


object Users: Table("users") {
    val id = int("id").autoGenerated()
    val username = string("username")
    val passwordHash = string("password_hash")
}


fun Users.hydrate(rs: ResultRow): User {
    return User(Username(rs[username]), PasswordHash.from(rs[passwordHash]))
}

fun Users.dehydrate(st: Dataset, user: User) {
    st[username] = user.username.value
    st[passwordHash] = user.passwordHash
}


val ResultRow.user: User get() = Users.hydrate(this)

val User.record: Dehydrator<Users> get() = {
    dehydrate(it, this@record)
}