package kickstart.security

import com.vtence.kabinet.DataSet
import com.vtence.kabinet.Dehydrator
import com.vtence.kabinet.ResultRow
import com.vtence.kabinet.Table


object Users: Table("users") {
    val id = int("id").autoGenerated()
    val username = string("username")
    val passwordHash = string("password_hash")
}


private fun Users.hydrate(rs: ResultRow): User {
    return User(Username(rs[username]), PasswordHash.from(rs[passwordHash]))
}

val ResultRow.user: User get() = Users.hydrate(this)


private fun Users.dehydrate(st: DataSet, user: User) {
    st[username] = user.username.value
    st[passwordHash] = user.passwordHash
}

val User.record: Dehydrator<Users> get() = {
    dehydrate(it, this@record)
}